# Generated by Django 4.1.5 on 2023-02-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_projects_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="cars",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="cars",
            name="file",
            field=models.FileField(default=1, upload_to="blender_files/"),
            preserve_default=False,
        ),
    ]
