# Generated by Django 4.1.5 on 2023-02-09 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0004_buildings_description_buildings_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="editbuildings",
            name="building",
        ),
        migrations.RemoveField(
            model_name="cars",
            name="file",
        ),
        migrations.RemoveField(
            model_name="characters",
            name="file",
        ),
        migrations.RemoveField(
            model_name="editcharacters",
            name="character",
        ),
        migrations.RemoveField(
            model_name="environments",
            name="file",
        ),
        migrations.RemoveField(
            model_name="projects",
            name="buildings",
        ),
        migrations.AddField(
            model_name="cars",
            name="url",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="characters",
            name="url",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="editcharacters",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.projects",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="environments",
            name="url",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Buildings",
        ),
        migrations.DeleteModel(
            name="EditBuildings",
        ),
    ]
