# Generated by Django 4.1.5 on 2023-02-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main_app",
            "0006_photo_remove_editcharacters_project_cars_photo_url_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="photo_url",
            field=models.CharField(blank=True, default=1, max_length=500),
            preserve_default=False,
        ),
    ]
