# Generated by Django 4.1.5 on 2023-02-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0007_alter_cars_photo_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cars",
            old_name="photo_url",
            new_name="photo",
        ),
        migrations.RemoveField(
            model_name="cars",
            name="url",
        ),
    ]
