# Generated by Django 4.1.5 on 2023-02-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0009_rename_photo_cars_photo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="characters",
            name="photo_url",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cars",
            name="description",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="cars",
            name="photo_url",
            field=models.CharField(max_length=500),
        ),
    ]
