# Generated by Django 4.1.5 on 2023-02-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0010_characters_photo_url_alter_cars_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="environments",
            name="photo_url",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
