# Generated by Django 4.1.5 on 2023-02-12 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0011_environments_photo_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projects",
            old_name="character",
            new_name="characters",
        ),
        migrations.RenameField(
            model_name="projects",
            old_name="environment",
            new_name="environments",
        ),
        migrations.RemoveField(
            model_name="environments",
            name="url",
        ),
    ]
